---
name: semantic-release

on:
  push:
    branches:
      - main

jobs:
  staging:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Semantic release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: '^16.0.0'
          extra_plugins: |
            @semantic-release/exec@^6.0.0
      - name: Release version ${{ steps.release.outputs.new_release_version }}
        uses: peter-evans/repository-dispatch@v2
        if: ${{ steps.release.outputs.new_release_published == 'true' }}
        with:
          token: ${{ secrets.GH_TOKEN }}
          event-type: version
          client-payload: '{"version": "${{ steps.release.outputs.new_release_version }}"}'
