---
name: semantic-release

on:
  push:
    branches:
      - '**'

jobs:
  version:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Semantic release
        id: release
        uses: cycjimmy/semantic-release-action@v3
        with:
          dry_run: true
          semantic_version: '^19.0.0'
      - name: Release version ${{ steps.release.outputs.new_release_version }} on ${{ github.ref_name }}
        uses: peter-evans/repository-dispatch@v2
        if: ${{ steps.release.outputs.new_release_published == 'true' }}
        with:
          token: ${{ secrets.GH_TOKEN }}
          event-type: version
          client-payload: '{"version": "${{ steps.release.outputs.new_release_version }}", "branch": "${{ github.ref_name }}"}'
